Fix typo in extension README.md
dotnet/vscode-dotnet-runtime pull request #536
Opened 2022-07-22 12:36 UTC by jogo-

2022-09-16 00:02 UTC, nagilson approved these changes

2022-10-14 23:21 UTC, nagilson commented
Thanks @jogo-  for spotting that typo and fixing it!

2022-10-14 23:22 UTC, nagilson commented
/azp run

2022-10-14 23:26 UTC, nagilson approved these changes

2022-11-18 19:17 UTC, SrujanNj approved these changes

2022-11-18 19:19 UTC, SrujanNj commented on vscode-dotnet-runtime-extension/README.md
> +3. **Servicing and floating versions**: It was difficult to ensure that extensions would use the latest releases, particularly without re-shipping.
Can somebody help me in this issue plssss...//?

2022-11-18 19:20 UTC, SrujanNj requested changes
Check this and please suggest the changes

2022-11-18 19:20 UTC, SrujanNj commented on vscode-dotnet-runtime-extension/README.md
> +3. **Servicing and floating versions**: It was difficult to ensure that extensions would use the latest releases, particularly without re-shipping.
13 ++

2022-11-18 21:39 UTC, nagilson commented
/azp run

2023-08-18 17:39 UTC, baronfel commented
Thanks again for this.

2023-08-18 17:39 UTC, merged